2018-08-08 16:41:22,621 ERROR:Exception on /index [GET] [in c:\users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\huanri\myproject\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 31, in index
    return render_template("index.html", title='Home', user=user, posts=posts
  File "c:\users\huanri\myproject\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\huanri\myproject\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\huanri\myproject\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\huanri\myproject\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html"%}
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\index.html", line 7, in block "content"
    <p>
  File "c:\users\huanri\myproject\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'form' is undefined
2018-08-08 18:47:05,009 ERROR:Exception on /index [GET] [in c:\users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\huanri\myproject\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 32, in index
    return render_template("index.html", title='Home', user=user, posts=posts, form=form
UnboundLocalError: local variable 'posts' referenced before assignment
2018-08-08 21:14:11,618 ERROR:Exception on /index [GET] [in c:\users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\huanri\myproject\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 32, in index
    return render_template("index.html", title='Home', user=user, posts=posts, form=form
UnboundLocalError: local variable 'posts' referenced before assignment
2018-08-08 21:15:20,375 ERROR:Exception on /index [GET] [in c:\users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\huanri\myproject\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 32, in index
    return render_template("index.html", title='Home', user=user, post=posts, form=form
UnboundLocalError: local variable 'posts' referenced before assignment
2018-08-08 21:15:23,615 ERROR:Exception on /index [GET] [in c:\users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\huanri\myproject\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 32, in index
    return render_template("index.html", title='Home', user=user, post=posts, form=form
UnboundLocalError: local variable 'posts' referenced before assignment
2018-08-08 21:20:41,053 ERROR:Exception on /index [GET] [in c:\users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-08-08 21:26:47,934 ERROR:Exception on /index [GET] [in c:\users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-08-08 21:26:50,176 ERROR:Exception on /index [GET] [in c:\users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\users\huanri\myproject\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
